image: docker:latest
services:
  - name: docker:dind
    command:
      - /bin/sh
      - -c
      - |
        echo "-----BEGIN CERTIFICATE-----
MIIFyjCCA7KgAwIBAgIUbDLqmxQLbxHhf8z+aahJ8oJ2Rw8wDQYJKoZIhvcNAQEL
BQAwbDELMAkGA1UEBhMCRVMxEjAQBgNVBAgMCUNhdGFsdW55YTESMBAGA1UEBwwJ
QmFyY2Vsb25hMRMwEQYDVQQKDApDeWJlcnByb29mMQswCQYDVQQLDAJDUDETMBEG
A1UEAwwKMTAuMS4xLjE1OTAeFw0yMTExMjIxMjM3MDZaFw0zMTExMjAxMjM3MDZa
MGwxCzAJBgNVBAYTAkVTMRIwEAYDVQQIDAlDYXRhbHVueWExEjAQBgNVBAcMCUJh
cmNlbG9uYTETMBEGA1UECgwKQ3liZXJwcm9vZjELMAkGA1UECwwCQ1AxEzARBgNV
BAMMCjEwLjEuMS4xNTkwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQDM
8u75tfzKqbQgYrU2uY0KGCKzk9SNBt5DAv2yrXkDh4kw+AIyvaswdP4WBw3KNNaY
8CxYdWQJ+ljAuD+n3vNLQXYwaGvz3QIsHokpS6034siku8BP/L7AxfbKMBQwWbb6
PFeJt5/A+JZaIsTxCizWg7xqZh64ToXBxxi/CrOsOo+Chi6jVa8QwIpTQWo8R2Ki
lgoD8BJh3Ikpg1aHLHnXsIV9/AdMPVy8KxZ7a7QSUBQnoZqwKRO90J8iUBjKeugK
wIfjLdESlLvGxG99qWJpKzgQFN4qfVR5w6zl7JwO8IN2YSB6kxs0Zf5JGLr81lo6
pKUP2hFJJJAHsgCf0kMUXgPQt5V2VkkyieVtAQgLpKGdM23kSYO0rseI6/eUQqGJ
lYQ+r3bPxKXHGY6u5Te23p1nZUItvvmgGMhHKzrdxNjCOYMgs7qiasOhSDJnrjx+
OUvMz7i05vempJeIwxq+69tk/s3ZxvezCU0vzBTFbkgoHghExfOtpvwGofsON/WJ
M0yCc5+TkpJ09ZsQT8MLtiETMQC/7POjaFBjIh0CM56w8nDfBO3DunTgYFARHDg9
h1AxdFZxAPXsTc7RqywYDSF0m1fCsuSPL1IHMHAv+eZhRJsBu4useD60v6rGSWZT
dJJpK0TNkphsZjHzRfFriq7NZ9IHVPpCTQzEGJ4vjwIDAQABo2QwYjAdBgNVHQ4E
FgQUoOyRxdMGAOSMXH9bjGsvabW96uIwHwYDVR0jBBgwFoAUoOyRxdMGAOSMXH9b
jGsvabW96uIwDwYDVR0TAQH/BAUwAwEB/zAPBgNVHREECDAGhwQKAQGfMA0GCSqG
SIb3DQEBCwUAA4ICAQBUUbqZzI9zms+7d5DdJuIeVFDZTWdNmT1tOCkPifNC7gA2
64xOSyyKjMU1AEpKUxMOHjHm+A7DdH+H7Ba5MCZPO07rJMxC/zd1VzAZuOFuDqDZ
bqR3tkoIcF5FWpl4UJG+GQT9zlX06MOk6nexiNz16aNRiJa+JGp6cn6gPfONZc6B
avfjmqU1mmzAobBaQgMzGqw6JRzHQXcY6sa6OGuail8O6F/gr+svJs5O71rvL2i4
eqjh2y7NkOKG6XLygKrsSdtkfaNS/PR1NSHq8rZ4Bfsc+ja4qjhbjn1qF+Bs7jxP
4SZX29WtJk7PbSwolF1eNBV+NM0kUnencyS4QnjieZMnI39EWbQ9H2YripkjxVrt
IW5nWKiKnClzdyBCdfAm/7iYxK8IlhL7+AGxzTEuHG5+4AKdJwJfK9e4AbILYe8a
mW84oDdGapqej1dwXpy/VpNydaClcs+DkYI9rI4xStmGnyD3cgylWrg4bmO+ZVWk
6w4rxcOVSQ42eggO6H/u09dxQPAfm9FXbc/ZaQ7GBCVH15Bm4pDiWmiAgHNKTb+Y
S2WQXvJtQBdO/Vvor3c1mwzhaECESTuqV2ix47lPY9RfkaWgYC01Ruqq5jtB1aoe
g7pGROnqFbGsV7aEKihSkkgbs8aJN1Wqxki9TTUweVrW2/mmQ6vmzheP3tEQHg==
-----END CERTIFICATE-----" > /etc/ssl/certs/10.1.1.159.crt || exit
        dockerd-entrypoint.sh || exit

build:
  stage: build
  script:
    - echo "JOB_TIMESTAMP $JOB_TIMESTAMP | COMMIT_HASH_SHORT $COMMIT_HASH_SHORT | COMMIT_BRANCH_OR_TAG $COMMIT_BRANCH_OR_TAG | REGISTRY_HOST $REGISTRY_HOST | REGISTRY_USER $REGISTRY_USER | REGISTRY_IMAGE $REGISTRY_IMAGE | CERTIFICATE_URL $CI_SERVER_TLS_CA_FILE"
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .

deploy:
  stage: deploy
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master
